# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Webster Crew
# Description of the Site
description: >-
  We are an Internet Crew that develops the future with the new technologies now.
  We live completely Online so we are flexible, fast and affordable for you and
  International Companies.
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico
# Site branding mode (select logo, title, logo+title)
site-branding: logo
# URL of Image of the Site
site-logo: /assets/images/logo.png
# URL of the Video of Custom Hero Video
herovideo: /assets/videos/hero-video.mp4

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/1280x720_Placeholder.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info@webstercrew.net
facebook_username: webstercrew
twitter_username: webstercrew
instagram_username: webstercrew
linkedin_username: webstercrew
github_username:  webstercrew
youtube_channel_id: webstercrew
reddit_username: webstercrew
behance_username: webstercrew
dribbble_username: webstercrew
spotify_username: webstercrew

# Google Analytics
google-analytics: UA-XXXXXXXXX-Y

# Disqus
disqus-shortname: webstercrew

# Name of the Author
author-name: Lorenzo Citro
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/webstercrew

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
