# WhatATheme
markdown: kramdown

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title, slogan and motto of the Site
title: Webster Crew
slogan: IT Solutions
meta-description: We develops the future now
# Description of the Site
description: >-
  We are an Internet Crew that develops the future with the new technologies now.
  We live completely Online so we are flexible, fast and affordable for you and
  International Companies.
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico
# Site branding mode. Select logo, title, logo+title
site-branding: logo
# URL of Image of the Site
site-logo: /assets/images/logo.png
# URL of the Video of Custom Hero Video
herovideo: /assets/videos/hero-video.mp4
# Case histories mode. Select link, download, modal
case-histories-type: link
# URL of the case-histories download
case-histories-link: /case-histories
case-histories-download: https://docs.google.com/document/d/1mdgrwqGQQZXpUEIwu5i_bkkCqOz8Mc27HZAgwrQtvyQ/export?format=pdf
# URL of the services images
services-image: /assets/images/services.png
# Services about text:
services-about: The Webster Crew space has been using the platform Jekyll written in Ruby by Tom Preston-Werner, GitHub's co-founder, it is distributed under the open source Massachusetts Institute of Technology License and customized in dynamic setting by Webster Crew. The icons are by Thenounproject. The Webster Crew brand is under Creative Commons License. Attribution - Non Commercial - No Derivative Works.

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/1280x720_Placeholder.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contactus@webstercrew.net
facebook_username: lorenzo.citro.dot.xero
# twitter_username: webstercrew
# instagram_username: webstercrew
linkedin_username: lorenzocitro
# github_username:  webstercrew
# youtube_channel_id: webstercrew
# reddit_username: webstercrew
# behance_username: webstercrew
# dribbble_username: webstercrew
# spotify_username: webstercrew

# Google Analytics
#google-analytics: UA-XXXXXXXXX-Y

# Disqus
# disqus-shortname: webstercrew

# Name of the Author
author-name: Lorenzo Citro
# URL for the Image of the Author
author-image: /assets/images/author.jpg
# 60 Words About the Author
author-about: We are an Internet Crew who deal with digital marketing and IT development. We worked for RCS - Rizzoli Corriere della Sera, Mondandori, Tiscali Italia, Tiscali UK, CondéNast and other international companies such as ENI and TotalErg (the latter in the ASO field). We are a research team managed by me, in fact I'm the IT Business Developer and I work on different projects. We offer outsourced services to support each project.<br/>My name is <strong>Lorenzo Citro</strong>, I am the founder and I'm a Digital Marketing Manager and IT Business Developer.<br/>My life is the Net.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/lorenzocitro/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
